module ThetaData
  module REST
    EODRow = Data.define(
      :created,
      :last_trade,
      :open,
      :high,
      :low,
      :close,
      :volume,
      :count,
      :bid_size,
      :bid_exchange,
      :bid,
      :bid_condition,
      :ask_size,
      :ask_exchange,
      :ask,
      :ask_condition,
    )

    OHLCRow = Data.define(
      :timestamp,
      :open,
      :high,
      :low,
      :close,
      :volume,
      :count,
      :vwap,
    )

    PriceRow = Data.define(
      :timestamp,
      :price,
    )

    TradeRow = Data.define(
      :timestamp,
      :sequence,
      :ext_condition1,
      :ext_condition2,
      :ext_condition3,
      :ext_condition4,
      :condition,
      :size,
      :exchange,
      :price,
    )

    QuoteRow = Data.define(
      :timestamp,
      :bid_size,
      :bid_exchange,
      :bid,
      :bid_condition,
      :ask_size,
      :ask_exchange,
      :ask,
      :ask_condition,
    )

    ExpirationRow = Data.define(:symbol, :expiration)

    StrikeRow = Data.define(:symbol, :strike)

    ContractRow = Data.define(:symbol, :expiration, :strike, :right)

    SnapshotPriceRow = Data.define(:timestamp, :symbol, :price)

    SnapshotOHLCRow = Data.define(
      :timestamp,
      :symbol,
      :open,
      :high,
      :low,
      :close,
      :volume,
      :count,
    )

    OptionOpenInterestRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :timestamp,
      :open_interest,
    )

    SnapshotTradeRow = Data.define(
      :timestamp,
      :symbol,
      :sequence,
      :size,
      :condition,
      :price,
    )

    SnapshotQuoteRow = Data.define(
      :timestamp,
      :symbol,
      :bid_size,
      :bid_exchange,
      :bid,
      :bid_condition,
      :ask_size,
      :ask_exchange,
      :ask,
      :ask_condition,
    )

    TradeQuoteRow = Data.define(
      :trade_timestamp,
      :quote_timestamp,
      :sequence,
      :ext_condition1,
      :ext_condition2,
      :ext_condition3,
      :ext_condition4,
      :condition,
      :size,
      :exchange,
      :price,
      :bid_size,
      :bid_exchange,
      :bid,
      :bid_condition,
      :ask_size,
      :ask_exchange,
      :ask,
      :ask_condition,
    )

    SnapshotOpenInterestRow = Data.define(
      :timestamp,
      :symbol,
      :expiration,
      :strike,
      :right,
      :open_interest,
    )

    OptionEODRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :created,
      :last_trade,
      :open,
      :high,
      :low,
      :close,
      :volume,
      :count,
      :bid_size,
      :bid_exchange,
      :bid,
      :bid_condition,
      :ask_size,
      :ask_exchange,
      :ask,
      :ask_condition,
    )

    OptionOHLCRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :timestamp,
      :open,
      :high,
      :low,
      :close,
      :volume,
      :count,
      :vwap,
    )

    OptionTradeRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :timestamp,
      :sequence,
      :ext_condition1,
      :ext_condition2,
      :ext_condition3,
      :ext_condition4,
      :condition,
      :size,
      :exchange,
      :price,
    )

    OptionQuoteRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :timestamp,
      :bid_size,
      :bid_exchange,
      :bid,
      :bid_condition,
      :ask_size,
      :ask_exchange,
      :ask,
      :ask_condition,
    )

    OptionSnapshotOHLCRow = Data.define(
      :timestamp,
      :symbol,
      :expiration,
      :strike,
      :right,
      :open,
      :high,
      :low,
      :close,
      :volume,
      :count,
    )

    OptionSnapshotTradeRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :timestamp,
      :sequence,
      :ext_condition1,
      :ext_condition2,
      :ext_condition3,
      :ext_condition4,
      :condition,
      :size,
      :exchange,
      :price,
    )

    OptionSnapshotQuoteRow = Data.define(
      :timestamp,
      :symbol,
      :expiration,
      :strike,
      :right,
      :bid_size,
      :bid_exchange,
      :bid,
      :bid_condition,
      :ask_size,
      :ask_exchange,
      :ask,
      :ask_condition,
    )

    OptionTradeQuoteRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :trade_timestamp,
      :quote_timestamp,
      :sequence,
      :ext_condition1,
      :ext_condition2,
      :ext_condition3,
      :ext_condition4,
      :condition,
      :size,
      :exchange,
      :price,
      :bid_size,
      :bid_exchange,
      :bid,
      :bid_condition,
      :ask_size,
      :ask_exchange,
      :ask,
      :ask_condition,
    )

    GreeksImpliedVolatilityRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :timestamp,
      :bid,
      :ask,
      :implied_vol,
      :iv_error,
      :underlying_timestamp,
      :underlying_price,
    )

    GreeksFirstOrderRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :timestamp,
      :bid,
      :ask,
      :delta,
      :theta,
      :vega,
      :rho,
      :epsilon,
      :lambda,
      :implied_vol,
      :iv_error,
      :underlying_timestamp,
      :underlying_price,
    )

    GreeksSecondOrderRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :timestamp,
      :bid,
      :ask,
      :gamma,
      :vanna,
      :charm,
      :vomma,
      :veta,
      :implied_vol,
      :iv_error,
      :underlying_timestamp,
      :underlying_price,
    )

    GreeksThirdOrderRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :timestamp,
      :bid,
      :ask,
      :speed,
      :zomma,
      :color,
      :ultima,
      :implied_vol,
      :iv_error,
      :underlying_timestamp,
      :underlying_price,
    )

    GreeksAllRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :timestamp,
      :bid,
      :ask,
      :delta,
      :theta,
      :vega,
      :rho,
      :epsilon,
      :lambda,
      :gamma,
      :vanna,
      :charm,
      :vomma,
      :veta,
      :vera,
      :speed,
      :zomma,
      :color,
      :ultima,
      :d1,
      :d2,
      :dual_delta,
      :dual_gamma,
      :implied_vol,
      :iv_error,
      :underlying_timestamp,
      :underlying_price,
    )

    GreeksEODRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :timestamp,
      :open,
      :high,
      :low,
      :close,
      :volume,
      :count,
      :bid_size,
      :bid_exchange,
      :bid,
      :bid_condition,
      :ask_size,
      :ask_exchange,
      :ask,
      :ask_condition,
      :delta,
      :theta,
      :vega,
      :rho,
      :epsilon,
      :lambda,
      :gamma,
      :vanna,
      :charm,
      :vomma,
      :veta,
      :vera,
      :speed,
      :zomma,
      :color,
      :ultima,
      :d1,
      :d2,
      :dual_delta,
      :dual_gamma,
      :implied_vol,
      :iv_error,
      :underlying_timestamp,
      :underlying_price,
    )

    TradeGreeksImpliedVolatilityRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :timestamp,
      :sequence,
      :ext_condition1,
      :ext_condition2,
      :ext_condition3,
      :ext_condition4,
      :condition,
      :size,
      :exchange,
      :price,
      :implied_vol,
      :iv_error,
      :underlying_timestamp,
      :underlying_price,
    )

    TradeGreeksFirstOrderRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :timestamp,
      :sequence,
      :ext_condition1,
      :ext_condition2,
      :ext_condition3,
      :ext_condition4,
      :condition,
      :size,
      :exchange,
      :price,
      :delta,
      :theta,
      :vega,
      :rho,
      :epsilon,
      :lambda,
      :implied_vol,
      :iv_error,
      :underlying_timestamp,
      :underlying_price,
    )

    TradeGreeksSecondOrderRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :timestamp,
      :sequence,
      :ext_condition1,
      :ext_condition2,
      :ext_condition3,
      :ext_condition4,
      :condition,
      :size,
      :exchange,
      :price,
      :gamma,
      :vanna,
      :charm,
      :vomma,
      :veta,
      :implied_vol,
      :iv_error,
      :underlying_timestamp,
      :underlying_price,
    )

    TradeGreeksThirdOrderRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :timestamp,
      :sequence,
      :ext_condition1,
      :ext_condition2,
      :ext_condition3,
      :ext_condition4,
      :condition,
      :size,
      :exchange,
      :price,
      :speed,
      :zomma,
      :color,
      :ultima,
      :implied_vol,
      :iv_error,
      :underlying_timestamp,
      :underlying_price,
    )

    TradeGreeksAllRow = Data.define(
      :symbol,
      :expiration,
      :strike,
      :right,
      :timestamp,
      :sequence,
      :ext_condition1,
      :ext_condition2,
      :ext_condition3,
      :ext_condition4,
      :condition,
      :size,
      :exchange,
      :price,
      :delta,
      :theta,
      :vega,
      :rho,
      :epsilon,
      :lambda,
      :gamma,
      :vanna,
      :charm,
      :vomma,
      :veta,
      :vera,
      :speed,
      :zomma,
      :color,
      :ultima,
      :d1,
      :d2,
      :dual_delta,
      :dual_gamma,
      :implied_vol,
      :iv_error,
      :underlying_timestamp,
      :underlying_price,
    )

    CalendarDayRow = Data.define(
      :type,
      :open,
      :close,
    )

    CalendarYearRow = Data.define(
      :date,
      :type,
      :open,
      :close,
    )
  end
end
