module ThetaData
  module Streaming
    module DisconnectReason
      UNSPECIFIED = -1
      INVALID_CREDENTIALS = 0
      INVALID_LOGIN_VALUES = 1
      INVALID_LOGIN_SIZE = 2
      GENERAL_VALIDATION_ERROR = 3
      TIMED_OUT = 4
      CLIENT_FORCED_DISCONNECT = 5
      ACCOUNT_ALREADY_CONNECTED = 6
      SESSION_TOKEN_EXPIRED = 7
      INVALID_SESSION_TOKEN = 8
      FREE_ACCOUNT = 9
      TOO_MANY_REQUESTS = 12
      NO_START_DATE = 13
      LOGIN_TIMED_OUT = 14
      SERVER_RESTARTING = 15
      SESSION_TOKEN_NOT_FOUND = 16
      SERVER_USER_DOES_NOT_EXIST = 17
      INVALID_CREDENTIALS_NULL_USER = 18

      NAMES = {
        UNSPECIFIED => "UNSPECIFIED",
        INVALID_CREDENTIALS => "INVALID_CREDENTIALS",
        INVALID_LOGIN_VALUES => "INVALID_LOGIN_VALUES",
        INVALID_LOGIN_SIZE => "INVALID_LOGIN_SIZE",
        GENERAL_VALIDATION_ERROR => "GENERAL_VALIDATION_ERROR",
        TIMED_OUT => "TIMED_OUT",
        CLIENT_FORCED_DISCONNECT => "CLIENT_FORCED_DISCONNECT",
        ACCOUNT_ALREADY_CONNECTED => "ACCOUNT_ALREADY_CONNECTED",
        SESSION_TOKEN_EXPIRED => "SESSION_TOKEN_EXPIRED",
        INVALID_SESSION_TOKEN => "INVALID_SESSION_TOKEN",
        FREE_ACCOUNT => "FREE_ACCOUNT",
        TOO_MANY_REQUESTS => "TOO_MANY_REQUESTS",
        NO_START_DATE => "NO_START_DATE",
        LOGIN_TIMED_OUT => "LOGIN_TIMED_OUT",
        SERVER_RESTARTING => "SERVER_RESTARTING",
        SESSION_TOKEN_NOT_FOUND => "SESSION_TOKEN_NOT_FOUND",
        SERVER_USER_DOES_NOT_EXIST => "SERVER_USER_DOES_NOT_EXIST",
        INVALID_CREDENTIALS_NULL_USER => "INVALID_CREDENTIALS_NULL_USER",
      }.freeze

      RECONNECTABLE = [
        TIMED_OUT,
        SESSION_TOKEN_EXPIRED,
        SERVER_RESTARTING,
      ].freeze

      def self.name(code)
        NAMES[code] || "UNKNOWN(#{code})"
      end

      def self.reconnectable?(code)
        RECONNECTABLE.include?(code)
      end
    end
  end
end
